### /predict

POST http://127.0.0.1:8000/predict/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data.csv"
Content-Type: application/json

< ./.private/heart_test.csv
--WebAppBoundary--
